language: php
php:
  - 5.6

env:
  global:
    - DATABASE='cidrupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

sudo: required
mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE


before_install:
  - composer self-update
  - export BASEDIR=${PWD}

install:
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer install

before_script:
  - drush status
  - sudo chmod -R 777 sites/all/modules
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`; export UNISH_DRUSH="${PWD}/drush"
  - rm -rf html
  - drush  make -y --force-complete drupal.make html
  - cd html
  - drush si -y standard --db-url=mysql://root@localhost/cidrupal --account-name=admin --account-pass=admin
  - drush runserver --server=builtin 8080 --strict=0 &
  - cd ..
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done

script:
  - $BASEDIR/vendor/bin/behat
